title: こがおニキに明日はない
description: >
  雑食系エンジニアが Processing の成果物をひたすら載せていきます。
  ちなみに仕事では Ruby, swift を書きつつ、趣味では Go や Unity をはじめ幅広い言語を触っています。
baseurl: ''
url: 'https://zdogma.github.io/'
twitter_username: z_dogma
github_username:  zdogma

# Build settings
markdown: kramdown
exclude: [vendor]

gems:
  - jekyll-auto-image

# Gem settings
## jekyll-auto-image
image: /images/default.jpg
